// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/components/rich-editor/tiptap-media-resize-main/src/App.vue')['default']
    AppProvider: typeof import('./src/components/global/AppProvider.vue')['default']
    CodeBlockComponent: typeof import('./src/components/rich-editor/CodeBlockComponent.vue')['default']
    CodeBlockCompotent: typeof import('./src/components/rich-editor/CodeBlockCompotent.vue')['default']
    HelloWorld: typeof import('./src/components/rich-editor/tiptap-media-resize-main/src/components/HelloWorld.vue')['default']
    ImagePreviewComponent: typeof import('./src/components/rich-editor/tiptap-extension-image-freely/src/ImagePreviewComponent.vue')['default']
    ImageResizeComponent: typeof import('./src/components/rich-editor/ImageResizeComponent.vue')['default']
    ImageRotateComponent: typeof import('./src/components/rich-editor/tiptap-extension-image-freely/src/ImageRotateComponent.vue')['default']
    ImageWithTool: typeof import('./src/components/rich-editor/tiptap-extension-image-freely/src/ImageWithTool.vue')['default']
    ImgPlaceholder: typeof import('./src/components/rich-editor/tiptap-extension-image-upload/src/imgPlaceholder.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NavTop: typeof import('./src/components/nav/NavTop.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NP: typeof import('naive-ui')['NP']
    NPopover: typeof import('naive-ui')['NPopover']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    QuillEditor: typeof import('./src/components/rich-editor/quillEditor.vue')['default']
    ResizableMediaNodeView: typeof import('./src/components/rich-editor/tiptap-media-resize-main/src/components/resizableMedia/ResizableMediaNodeView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tiptap: typeof import('./src/components/rich-editor/tiptap-media-resize-main/src/components/Tiptap.vue')['default']
    TipTapEditor: typeof import('./src/components/rich-editor/tipTapEditor.vue')['default']
  }
}
